### ISSUE TITLE
As a website visitor, I want a carousel feature on the homepage that transitions between three distinct photos, So that I can get a visual overview of Cole Wright's team, their work, and customer satisfaction.

### ISSUE THREAD

**Issue by myDeveloperJourney** [MDJ-Studios/the-wright-fence-co-site#2]
### Acceptance Criteria:

- [ ] **Photo Inclusion**: Include three photos in the carousel: one of Cole Wright and his employees, one showcasing Cole Wright's work for a customer, and one of a satisfied customer.
- [ ] **Automatic Transition**: Carousel automatically transitions between photos every 3 seconds.
- [ ] **Transition Smoothness**: Ensure smooth and seamless transitions between photos.
- [ ] **Manual Navigation**: Provide manual navigation options like arrows or dots for user control.
- [ ] **Responsive Design**: Carousel should be responsive and display correctly on different devices and screen sizes.
- [ ] **Accessibility Compliance**: Ensure carousel is accessible, including alternative text for each photo and keyboard navigability.
- [ ] **Loading Efficiency**: Carousel should load efficiently, without impacting the overall website load time significantly.
- [ ] **Visual Appeal**: Design of the carousel should complement the website's aesthetic.
- [ ] **Consistent Quality**: All photos should be high resolution and reflect the professional standards of Cole Wright’s services.

**Comment by Clue355** [comment]
I'll take this one next
